# Generated by Django 3.2.13 on 2022-04-25 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20220424_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Upload Date'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voting_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Voting Date'),
        ),
    ]
