# Generated by Django 3.2.13 on 2022-04-26 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20220425_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='upload_date',
            field=models.DateField(verbose_name='Upload Date'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voting_date',
            field=models.DateField(verbose_name='Voting Date'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('voting_date', models.DateField(verbose_name='Voting Date')),
                ('winning_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='voting.menu', verbose_name='Winning Menu')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'ordering': ['id'],
            },
        ),
    ]
