# Generated by Django 3.2.13 on 2022-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20220426_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='winning_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Winning Streak'),
        ),
    ]
